#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -std=c++11 -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -lSDL2 -lSDL2_ttf

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = program

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/ColorSystem.o $(OBJDIR_RELEASE)/src/Draw.o $(OBJDIR_RELEASE)/src/Objeto3D.o

all: release

clean: clean_release

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/ColorSystem.o: src/ColorSystem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ColorSystem.cpp -o $(OBJDIR_RELEASE)/src/ColorSystem.o

$(OBJDIR_RELEASE)/src/Draw.o: src/Draw.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Draw.cpp -o $(OBJDIR_RELEASE)/src/Draw.o

$(OBJDIR_RELEASE)/src/Objeto3D.o: src/Objeto3D.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Objeto3D.cpp -o $(OBJDIR_RELEASE)/src/Objeto3D.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_release after_release clean_release

